# Generated by Django 5.2.5 on 2025-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportswearBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='Brand')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('link', models.URLField(max_length=500, verbose_name='Link E-Commerce')),
                ('category', models.CharField(choices=[('YOGA', 'Yoga'), ('PILATES', 'Pilates'), ('BOTH', 'Yoga & Pilates')], default='BOTH', max_length=10, verbose_name='Kategori Olahraga')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Logo Brand')),
            ],
        ),
    ]
