# Generated by Django 5.2.5 on 2025-10-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportswearbrand',
            name='category',
        ),
    ]
