# Generated by Django 5.2.5 on 2025-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0002_remove_sportswearbrand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportswearbrand',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='sportswearbrand',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sportswearbrand',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Brand Logo'),
        ),
    ]
