# Generated by Django 5.2.7 on 2025-11-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0003_alter_sportswearbrand_brand_name_and_more'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sportswear.sportswearbrand')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_reviews', to='timeline.post')),
            ],
        ),
    ]
