# Generated by Django 5.2.7 on 2025-12-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0004_brandreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandreview',
            name='post',
        ),
        migrations.AddField(
            model_name='brandreview',
            name='location',
            field=models.CharField(default='Jakarta', max_length=50),
        ),
        migrations.AddField(
            model_name='brandreview',
            name='rating_value',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='brandreview',
            name='review_text',
            field=models.TextField(default='No review provided', verbose_name='Review Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sportswear_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportswearbrand',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='sportswearbrand',
            name='category_tag',
            field=models.CharField(default='Casual', max_length=50, verbose_name='Category Tag (Yoga, Running, etc.)'),
        ),
    ]
