# Generated by Django 5.2.7 on 2025-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0005_remove_brandreview_post_brandreview_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportswearbrand',
            name='category_tag',
            field=models.CharField(default='Yoga', max_length=50, verbose_name='Category Tag (Yoga, Pilates, etc.)'),
        ),
    ]
