# Generated by Django 5.2.7 on 2025-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0006_alter_sportswearbrand_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportswearbrand',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=4, verbose_name='Average Rating'),
        ),
    ]
