# Generated by Django 5.2.5 on 2025-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportswear', '0007_alter_sportswearbrand_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportswearbrand',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=100, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='sportswearbrand',
            name='link',
            field=models.URLField(max_length=1000, verbose_name='Link E-Commerce'),
        ),
        migrations.AlterField(
            model_name='sportswearbrand',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL Brand Logo'),
        ),
    ]
