# Generated by Django 5.2.5 on 2025-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
            ],
        ),
    ]
