# Generated by Django 5.2.5 on 2025-12-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='owner',
        ),
    ]
