# Generated by Django 5.2.8 on 2025-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
