# Generated by Django 5.2.7 on 2025-11-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_thumbnail_url'),
        ('sportswear', '0003_alter_sportswearbrand_brand_name_and_more'),
        ('timeline', '0005_alter_comment_author_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sportswear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='sportswear.sportswearbrand'),
        ),
    ]
