# Generated by Django 5.1.3 on 2025-10-22 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_studio', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('kota', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('gmaps_link', models.URLField(blank=True, null=True)),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
        ),
    ]
