# Generated by Django 5.1.3 on 2025-10-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_studio_gmaps_link_alter_studio_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='nomor_telepon',
            field=models.CharField(max_length=20),
        ),
    ]
