# Generated by Django 5.1.3 on 2025-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_studio_nomor_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
