# Generated by Django 5.2.5 on 2025-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_studio_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='rating',
            field=models.FloatField(),
        ),
    ]
