# Generated by Django 5.2.7 on 2025-10-17 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_studio', models.CharField(max_length=100)),
                ('kota', models.CharField(choices=[('jakarta', 'Jakarta'), ('bogor', 'Bogor'), ('depok', 'Depok'), ('tangerang', 'Tangerang'), ('bekasi', 'Bekasi')], max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
        ),
    ]
