# Generated by Django 5.2.7 on 2025-10-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='kota',
        ),
        migrations.AddField(
            model_name='studio',
            name='gmaps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
