# Generated by Django 5.2.7 on 2025-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_city_userprofile_kota_studio_gmaps_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='kota',
            field=models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kota',
            field=models.CharField(blank=True, choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=20, null=True),
        ),
    ]
