# Generated by Django 5.1.3 on 2025-10-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studio_kota_alter_userprofile_kota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studio',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
