# Generated by Django 5.1.3 on 2025-10-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
