# Generated by Django 5.2.7 on 2025-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_level_alter_resource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
